In [32]:
import numpy as np
from scipy.linalg import expm, sinm, cosm
from scipy.sparse import csc_matrix
from scipy.sparse.linalg import expm as sexpm

In [8]:
expm(np.zeros((2,2)))

array([[1., 0.],
       [0., 1.]])

In [13]:
np.diag(np.ones((5)))

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [14]:
np.array([[1., 0., 0., 1., 1.],
          [0., 1., 0., 1., 1.],
          [0., 0., 1., 0., 0.],
          [1., 1., 0., 1., 0.],
          [1., 1., 0., 0., 1.]])

array([[1., 0., 0., 1., 1.],
       [0., 1., 0., 1., 1.],
       [0., 0., 1., 0., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 0., 1.]])

In [21]:
expm(np.array([[1., 0., 0., 1., 1.],
               [0., 1., 0., 1., 1.],
               [0., 0., 1., 1., 1.],
               [1., 1., 1., 1., 0.],
               [1., 1., 1., 0., 1.]]))

array([[7.09869007, 4.38040824, 4.38040824, 6.37880464, 6.37880464],
       [4.38040824, 7.09869007, 4.38040824, 6.37880464, 6.37880464],
       [4.38040824, 4.38040824, 7.09869007, 6.37880464, 6.37880464],
       [6.37880464, 6.37880464, 6.37880464, 9.28889419, 6.57061236],
       [6.37880464, 6.37880464, 6.37880464, 6.57061236, 9.28889419]])

In [30]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [18]:
expm(np.array([[1., 0., 0., 1., 0.],
               [0., 1., 0., 0., 1.],
               [0., 0., 1., 0., 0.],
               [1., 0., 0., 1., 0.],
               [0., 1., 0., 0., 1.]]))

array([[4.19452805, 0.        , 0.        , 3.19452805, 0.        ],
       [0.        , 4.19452805, 0.        , 0.        , 3.19452805],
       [0.        , 0.        , 2.71828183, 0.        , 0.        ],
       [3.19452805, 0.        , 0.        , 4.19452805, 0.        ],
       [0.        , 3.19452805, 0.        , 0.        , 4.19452805]])

In [28]:
%timeit expm(np.diag(np.ones((500)))) # expm does not handle diagonal matrices differently

17.7 ms ± 2.51 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [29]:
%timeit np.exp(np.ones((500)))

5.02 µs ± 32.5 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [35]:
%timeit sexpm(np.array([[1., 0., 0., 1., 1.],[0., 1., 0., 1., 1.],[0., 0., 1., 1., 1.],[1., 1., 1., 1., 0.],[1., 1., 1., 0., 1.]]))

195 µs ± 694 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [36]:
%timeit expm(np.array([[1., 0., 0., 1., 1.],[0., 1., 0., 1., 1.],[0., 0., 1., 1., 1.],[1., 1., 1., 1., 0.],[1., 1., 1., 0., 1.]]))

206 µs ± 2.11 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [40]:
%timeit a = np.exp(np.ones(10))

2.47 µs ± 11.9 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [39]:
%timeit a,b=np.exp(np.ones(5)),np.exp(np.ones(5))

4.87 µs ± 9.32 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [ ]:
# test matrix multiplication speed

In [44]:
%timeit np.zeros((500,500))@np.ones(500)

60.1 µs ± 90.9 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [67]:
a = [1]
b = [2]
c = [3]
mat = [a,b,c]

In [68]:
def func(a,b,c):
    a[0],b[0],c[0]=4,5,6
    return a,b,c

In [70]:
func(a,b,c)

([4], [5], [6])

In [71]:
mat

[[4], [5], [6]]

In [72]:
z = [1]

In [73]:
x = z

In [75]:
x[0] = 5

In [76]:
x

[5]

In [77]:
z

[5]

In [98]:
ψb = np.array([1,2,3,4,5,6,7,8,9,0])

In [90]:
%timeit np.exp(ψb)

927 ns ± 8.03 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [99]:
ψ = np.array([[1],[2],[3],[4],[5],[6],[7],[8],[9],[0]])

In [88]:
%timeit np.exp(ψ)

1.08 µs ± 7.57 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [100]:
ψref = [ψ[0],ψ[1]]

In [101]:
ψref

[array([1]), array([2])]

In [102]:
ψ[0][0] = 12 
ψ[1][0] = 13

In [103]:
ψref

[array([12]), array([13])]

In [104]:
ψ

array([[12],
       [13],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [ 0]])

In [105]:
np.exp(ψref)

array([[162754.791419  ],
       [442413.39200892]])