In [1]:
import numpy as np

In [2]:
a = [1]
b = [2]
c = [3]
mat = [a,b,c]

In [3]:
def func(a,b,c):
    a[0],b[0],c[0]=4,5,6
    return a,b,c

In [4]:
func(a,b,c)

([4], [5], [6])

In [5]:
mat

[[4], [5], [6]]

In [6]:
z = [1]

In [7]:
x = z

In [8]:
x[0] = 5

In [9]:
x

[5]

In [10]:
z

[5]

In [47]:
ψb = np.array([1,2,3,4,5,6,7,8,9,0])

In [12]:
%timeit np.exp(ψb)

852 ns ± 11.6 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [48]:
ψ = np.array([[1],[2],[3],[4],[5],[6],[7],[8],[9],[0]])

In [14]:
%timeit np.exp(ψ)

1.05 µs ± 5.64 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [49]:
ψ[0]

array([1])

In [50]:
ψref = [ψ[0],ψ[1],ψ[2],ψ[3],ψ[4],ψ[5],ψ[6],ψ[7],ψ[8],ψ[9]]

In [51]:
ψref

[array([1]),
 array([2]),
 array([3]),
 array([4]),
 array([5]),
 array([6]),
 array([7]),
 array([8]),
 array([9]),
 array([0])]

In [52]:
ψ[0][0] = 12 
ψ[1][0] = 13

In [55]:
%timeit np.exp(ψref)

4.76 µs ± 36.2 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [56]:
%timeit np.exp(ψ)

1.04 µs ± 4.66 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


NEW

In [58]:
ψb = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

In [59]:
ψc = ψb

In [64]:
ψb[0] = 15

In [66]:
mask = [0,0,2,4]

In [67]:
ψc[mask]

array([15, 15,  3,  5])